export const actions = Object.freeze({
  // Authentication
  AUTH_INITIALIZE: 'AUTH_INITIALIZE',
  AUTH_CONNECT_SUCCESS: 'AUTH_CONNECT_SUCCESS',
  AUTH_CONNECT_ERROR: 'AUTH_CONNECT_ERROR',
  AUTH_DISCONNECT: 'AUTH_DISCONNECT'
});
